### ISSUE TITLE
Keyboard and api error

### ISSUE THREAD

**Issue by BimoSora2** [hiiruki/CheckRek#1]
Ada beberapa api error seperti DANA, GOPAY, LINK AJA, dll dan keyboard ctrl+c memunculkan tulisan. Tolong perintah delete text difungsikan. Hanya OVO yang bekerja.
```
/CheckRek/checkrek.py", line 66, in <module>
    bank_choice = int(input("\nPlease choose a bank/e-wallet from the menu (use number 1-17): "))
KeyboardInterrupt
```

**Comment by hiiruki** [comment]
Untuk beberapa E-Wallet memang kadang ada yang tidak bisa, dikarenakan ada kesalahan pada API pihak ketiga, disini saya hanya membuat versi CLI dari API tersebut.

Lalu untuk error `KeyboardInterrupt` pada saat `CTRL + C` itu memang bawaan dari Python sendiri.

**Comment by arunika0** [comment]
> Untuk beberapa E-Wallet memang kadang ada yang tidak bisa, dikarenakan ada kesalahan pada API pihak ketiga, disini saya hanya membuat versi CLI dari API tersebut.
> 
> Lalu untuk error `KeyboardInterrupt` pada saat `CTRL + C` itu memang bawaan dari Python sendiri.

jadi untuk solusi notif API Request Failed memang tidak ada dikarenakan menggunakan API third party? soalnya dicoba untuk semua E-Wallet pada muncul notif sama "API Request Failed"
